In [27]:
import numpy as np
import cv2


In [28]:
img = cv2.imread('./data/friend_lagi.jpeg')

cv2.imshow('image',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
# load cascade 
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [33]:
image = img.copy()
# satu = convert gambar ke grayscale
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# dua = menerapkan grayscale ke cascade classifier
face_rect = haar.detectMultiScale(gray,1.3,5)
#dua = gambar box untuk wajah
for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('detected faces',image)
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
print(face_rect)

[[ 85  70  62  62]
 [168  59  60  60]
 [265  60  62  62]]
